### ISSUE TITLE
給湯負荷の計算方法の実装(1日単位)

### ISSUE THREAD

**Issue by HisashiMiura** [BRI-EES-House/Logic-EES-WEB#6]
- 仕様書(2018/4月時点)をベースに実装
- 太陽熱給湯についても本来であれば実装すべきであるが、給湯負荷の時間単位評価および熱源機の時間単位評価の検討(東大の前先生担当)に早く入りたいため、とりあえずは太陽熱給湯を除く給湯負荷の計算方法の実装(1日単位)を急ぐ。

**Comment by SMizutani** [comment]
承知しました。

**Comment by SMizutani** [comment]
1日単位の計算の実装終わりました。
この後、年合計の計算、テストケースの連続計算を実装していきます。

**Comment by HisashiMiura** [comment]
お疲れ様でした！
